on:
  release:
    types: [created]

name: Release

jobs:
  build-release:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Disable windows for now as it breaks
          #- target: x86_64-pc-windows-gnu
          #  archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip tar.gz
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

  homebrew:
    name: Bump Homebrew Formula
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: gpterm
          formula-path: Formula/gpterm.rb
          homebrew-tap: frikksol/frikksol
          base-branch: main
          download-url: https://github.com/frikksol/gpterm/releases/download/${{ github.ref_name }}/gpterm_${{ github.ref_name }}_x86_64-apple-darwin.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
